= Spring Boot Lab - From Zero to Microservice in Five Minutes
In this lab you'll be creating from scratch a simple RESTful service in a few short minutes using Spring Boot and the Spring Initializr.

== Generate a starter project

. Navigate to the Spring Initializr at http://start.spring.io
+
<Insert screenshot here>

. Search for and add a Web dependency
+
<Insert screenshot here>

. Switch to the full version of Spring Initializr to see a complete listing of configuration options
<Insert screenshot here>
. Click "Generate Project" and unzip the project

== Implement the REST service

. Build and run your application
+
----
$ ./mvnw spring-boot:run
[INFO] Scanning for projects...
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] Building demo 0.0.1-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO]
[INFO] >>> spring-boot-maven-plugin:1.4.2.RELEASE:run (default-cli) > test-compile @ demo >>>
[INFO]

...

  .   ____          _            __ _ _
 /\\ / ___'_ __ _ _(_)_ __  __ _ \ \ \ \
( ( )\___ | '_ | '_| | '_ \/ _` | \ \ \ \
 \\/  ___)| |_)| | | | | || (_| |  ) ) ) )
  '  |____| .__|_| |_|_| |_\__, | / / / /
 =========|_|==============|___/=/_/_/_/
 :: Spring Boot ::        (v1.4.2.RELEASE)

...
2016-12-08 15:05:09.597  INFO 30080 --- [           main] s.b.c.e.t.TomcatEmbeddedServletContainer : Tomcat started on port(s): 8080 (http)
2016-12-08 15:05:09.601  INFO 30080 --- [           main] com.example.DemoApplication              : Started DemoApplication in 2.4 seconds (JVM running for 9.305)
----

. Your application is now running and you can test it at http://localhost:8080
+
<Insert screenshot here>
+
The error message is to be expected as there's currently no code that handles the root endpoint of this application.

. Import the project in your IDE. 
. Create a class named HelloController in the package com.example that looks as follows
+
----
package com.example;

import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RestController;

@RestController
public class HelloController {
    @RequestMapping("/")
    public String helloWorld() {
        return "Hello World!";
    }
}
----

. Restart your application, either by starting the DemoApplication class in your IDE or running ./mvnw spring-boot:run on your commandline
. Test the application on http://localhost:8080
+
<Insert screenshot here>

== Build and push to Cloud Foundry

. Build application
+
----
$ ./mvnw package
[INFO]
[INFO] --- maven-jar-plugin:2.6:jar (default-jar) @ demo ---
[INFO] Building jar: target/demo-0.0.1-SNAPSHOT.jar
[INFO]
[INFO] --- spring-boot-maven-plugin:1.4.2.RELEASE:repackage (default) @ demo ---
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 7.484 s
[INFO] Finished at: 2016-12-08T16:02:40-05:00
[INFO] Final Memory: 31M/323M
[INFO] ------------------------------------------------------------------------
----

. Push application to Cloud Foundry
+
----
$ cf push hello-world -p target/demo-0.0.1-SNAPSHOT.jar --random-route -m 512m
Creating app hello-world in org bboe-org / space development as bboe...

...

Showing health and status for app hello-world in org bboe-org / space development as bboe...
OK

requested state: started
instances: 1/1
usage: 512M x 1 instances
urls: hello-world-unpetulant-condignity.cfapps.haas-74.pez.pivotal.io
last uploaded: Thu Dec 8 21:12:26 UTC 2016
stack: cflinuxfs2
buildpack: java-buildpack=v3.8.1-offline-https://github.com/cloudfoundry/java-buildpack.git#29c79f2 java-main open-jdk-like-jre=1.8.0_91-unlimited-crypto open-jdk-like-memory-calculator=2.0.2_RELEASE spring-auto-reconfiguration=1.10.0_RELEASE

     state     since                    cpu     memory           disk         details
#0   running   2016-12-08 04:13:00 PM   32.6%   264.8M of 512M   137M of 1G
----

. Test the application at the endpoint generated by Cloud Foundry
+
<insert picture here>

== Cleanup
. Delete application from Cloud Foundry
+
----
$ cf delete hello-world


Really delete the app hello-world?> y
Deleting app hello-world in org bboe-org / space development as bboe...
OK
----
